"use client";

import { useCallback, useMemo } from "react";
import { useConnection, useWallet } from "@solana/wallet-adapter-react";
import { Program, AnchorProvider, BN } from "@coral-xyz/anchor";
import { PublicKey, SystemProgram } from "@solana/web3.js";
import { randomBytes } from "crypto";
import { PROGRAM_ID, CLUSTER_OFFSET } from "./constants";

// We'll load IDL dynamically since it's generated by arcium build
let cachedIdl: any = null;

export function useProgram() {
  const { connection } = useConnection();
  const wallet = useWallet();

  const provider = useMemo(() => {
    if (!wallet.publicKey || !wallet.signTransaction) return null;
    return new AnchorProvider(connection, wallet as any, {
      commitment: "confirmed",
    });
  }, [connection, wallet]);

  const program = useMemo(() => {
    if (!provider || !cachedIdl) return null;
    return new Program(cachedIdl, provider);
  }, [provider]);

  return { program, provider, connection, wallet };
}

// PDA derivations
export function getDaoPda(authority: PublicKey, daoId: number): PublicKey {
  return PublicKey.findProgramAddressSync(
    [
      Buffer.from("dao"),
      authority.toBuffer(),
      new BN(daoId).toArrayLike(Buffer, "le", 4),
    ],
    PROGRAM_ID
  )[0];
}

export function getProposalPda(daoPda: PublicKey, proposalId: number): PublicKey {
  return PublicKey.findProgramAddressSync(
    [
      Buffer.from("proposal"),
      daoPda.toBuffer(),
      new BN(proposalId).toArrayLike(Buffer, "le", 4),
    ],
    PROGRAM_ID
  )[0];
}

export function getCommentPda(proposalPda: PublicKey, commentId: number): PublicKey {
  return PublicKey.findProgramAddressSync(
    [
      Buffer.from("comment"),
      proposalPda.toBuffer(),
      new BN(commentId).toArrayLike(Buffer, "le", 4),
    ],
    PROGRAM_ID
  )[0];
}

export function newComputationOffset(): BN {
  return new BN(randomBytes(4), "hex");
}
